### ISSUE TITLE
Not an issue, just question on kindly provided example.

### ISSUE THREAD

**Issue by Mallowan** [rapha-dev/examples#1]
`if (MainFormsPlc != null) { var value = MainFormsPlc.Read("DB9.DBD2"); }`
tell me please for what do you check if MainFormsPlc is not equal 'null'?
I'm asking because I have in my code following:
`private Plc plc = null;` And it's working.

P.S. I'm not much familiar with such kind of sites based on pretty odd forum engines. Especially highly recommended **Stackoverflow**.

**Comment by rapha-dev** [comment]
Ah, I see...
Before showing SubForm the Plc instance is passed to the newly created SubForm.
```
// pass Plc instance to SubForm
form.MainFormsPlc = MyPlc;
```
While executing button_Click in the SubForm you might not want to have a NullReferenceException before doing PLC actions (using `MainFormsPlc` object).

I prefer to catch such issues before they actually get a problem (Exception), in this case it is a _user_ that clicks the button. I don't know _when_ the user clicks it, maybe in some mid-action while the Form (Form1) is still initializing. This might not happen in this simple example but may in some advanced setups.

Where do you have `private Plc plc = null;` in your project?
If it is in your MainForm and you use it (`Open()`, `Read()` or `Write()`) you don't need to `Open()` in SubForm again. `MyPlc` (or your `plc`) points just to the same instance as `MainFormsPlc` in the SubForm.

**Comment by rapha-dev** [comment]
@Mallowan 
I find it neat to have versioning support built-in, so GitHub reflects all changes. I am also still learning to utilize GitHub correctly. There are many features but this applies to most other platforms as well.

**Comment by Mallowan** [comment]
> Where do you have private Plc plc = null; in your project?
If it is in your MainForm and you use it (Open(), Read() or Write()) you don't need to Open() in SubForm again. MyPlc (or your plc) points just to the same instance as MainFormsPlc in the SubForm.

MainForm, some pieces of code.
```
 public partial class MainForm : Form
    {
        private Plc plc = null;
        private ErrorCode errCode;
        public bool? CPUisConnected; //By certain reasons this variable must be nullable, so it's "bool?". 
                                     //Because normal boolean variable is always 'false' by default. So while application starting it causes fail " PLC connection is broken" at once. 
                                     //The connection itself is in process of establishing in that moment, though. 

 #region PLC connection and errors handling

            //////////////////////////////////-PLC connection and errors handling-//////////////////////////////////

            try
            {
                plc = new Plc(CpuType.S71500, "100.1.1.70", 0, 1);

                if (!plc.IsAvailable) throw new Exception("PLC not responding to ping");

                errCode = plc.Open();

                if (errCode != ErrorCode.NoError) throw new Exception(plc.LastErrorString);



            }

            catch (Exception ex)
            {
                //MessageBox.Show(ex.Message, "Attention!",MessageBoxButtons.OK,MessageBoxIcon.Error);
                Form_ErrorBox.Show(ex.Message, "Attention!", "OK");

            }

            #endregion

```
Also I would like ask about following:
I noticed that for app there's no matter if I put '0' or '1' in 'Slot' value in the following line: 

> plc = new Plc(CpuType.S71500, "100.1.1.70", 0, 0); 

in real hardware configuration I have 'Slot' =1. Look at the pic attached.  However it's working with '0' as well. For numbers above '1' it issues a fail as it should be. 
And situation with "Rack" is much better. It works exactly as it should be, I think.


![device_overview](https://user-images.githubusercontent.com/37699980/42104881-007baee8-7bd7-11e8-9e79-f65c120a28ac.png)

Mallowan

**Comment by rapha-dev** [comment]
I assume the region PLC is in Form's construct so plc will be instanciated when you open a SubForm. That should be fine, it can be private.

Second, Slot is irrelevant on 1500, I have seen this in NetToPlcSim also. Unsure if Rack is working, don't have a suitable setup ATM.

**Comment by rapha-dev** [comment]
Feel free to re-open.
